### PR TITLE
Removed BARS profiling

### PR DESCRIPTION
**Pull request by KevinMayfield**
As abovr

### CODE REVIEW

**Review by NaminderSoorma — CHANGES_REQUESTED** [review]
I’m rejecting it as there are still Codesystems unique to BARS and other bits that would show duplication:

https://simplifier.net/nhsdigital/~resources?text=bars&category=Profile|ValueSet|CodeSystem|Extension|SearchParameter|CompartmentDefinition|CapabilityStatement|OperationDefinition|NamingSystem|ConceptMap|StructureMap|ImplementationGuide|TestScript|DataElement|GraphDefinition|ExpansionProfile|Example|LogicalModel|Text|Image|Layout|PackageManifest|MappingFile&sortBy=DisplayName

I think the only Codesystems that should remain in NHS D are the shared:

https://simplifier.net/nhsdigital/message-events-bars

https://simplifier.net/nhsdigital/message-reason-bars

**Comment by KevinMayfield** [comment]
Have removed all BARS CodeSystems, except for https://fhir.nhs.uk/CodeSystem/message-category-servicerequest

**Review by NaminderSoorma — CHANGES_REQUESTED** [review]
You need to keep:

CodeSystem/BARS-message-events.json

And 

CodeSystem/BARS-message-reason.json

In the NHS D as I removed them from BARS a while ago, they would be intended to be used by wider projects just like the categories.

**Comment by KevinMayfield** [comment]
Two codesystems readded

**Review by NaminderSoorma — APPROVED** [review]

**Comment by NaminderSoorma** [comment]
The files looks ok now. Approving.

**Pull request merged**
