### PR TITLE
Added PATIENT_SENSITIVE code for ERS

### PR DESCRIPTION
**Pull request by ryma2fhir**

### CODE REVIEW

**Comment by ryma2fhir** [comment]
@DaveBarnet Suggest upping version to 1.1.0 and updating the date

**Comment by DaveBarnet** [comment]
[like]  BARNET, David (NHS ENGLAND - X26) reacted to your message:
________________________________

**Comment by DaveBarnet** [comment]
Typically, I can't sign in ...

GitHub Enterprise Cloud - Organization
Sorry, but we're having trouble with signing you in.
AADSTS50105: Your administrator has configured the application GitHub Enterprise Cloud - Organization ('889cba22-fa4c-4913-b1df-2913f2e8f6d0') to block users unless they are specifically granted ('assigned') access to the application. The signed in user ***@***.***' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application.

**Review by johngeo — APPROVED** [review]
Looks fine to me, CodeSystem, has been upversioned and a new code added. 
"code": "PATIENT_SENSITIVE",

What about the ValueSet that uses this codeSystem, does it need a description update etc...?


 

</figure><p>&nbsp;</p>
</body>
</html>

**Review by digitalhealthmartin — APPROVED** [review]

**Review by vickyjaiswal0308 — APPROVED** [review]

**Comment by ryma2fhir** [comment]
Associated ValueSet does not have any expansion so no need to update https://github.com/NHSDigital/NHSEngland-FHIR-ImplementationGuide/blob/Feature-ersErrorCodeChange/ValueSet/NHSDigital-OperationOutcome-Codes.xml

**Pull request merged**
