### PR TITLE
Feature/feature/iops 1544 nhs digital observation

### PR DESCRIPTION
**Pull request by ryma2fhir**

### CODE REVIEW

**Review by declankieran — COMMENTED** [review]
I've no issue with the content overall, but I think maybe @omarisgreat or @KevinMayfield , should just have a look at the DocumentReference examples where the context element was removed so it now passes validation to give a final approve on it.  

It was passing before, and it doesn't look like there are any issues with the CodeSystem that is returning the 404's, so it would be worth raising a ticket to see if its a bug in the HAPI code (trying to resolve via URL rather locally, it should be able to locally), or there is some subtle mistake in the actual FHIR resources.

**Comment by omarisgreat** [comment]
> I've no issue with the content overall, but I think maybe @omarisgreat or @KevinMayfield , should just have a look at the DocumentReference examples where the context element was removed so it now passes validation to give a final approve on it.
> 
> It was passing before, and it doesn't look like there are any issues with the CodeSystem that is returning the 404's, so it would be worth raising a ticket to see if its a bug in the HAPI code (trying to resolve via URL rather locally, it should be able to locally), or there is some subtle mistake in the actual FHIR resources.

No issue with the DocumentReferences from my side. The CodeSystem/ValueSet all look fine to me as well, and the StructureDefinitions themselves are not throwing up errors, so must be a bug in the terminology validation code.

**Comment by KevinMayfield** [comment]
I think the issue here is the way it was profiled. 

I recall having similar issues with NHSDigital-Task and I split a ValueSet containing several CodeSystems into three and also used slicing in the profile.

**Comment by KevinMayfield** [comment]
Do we have a (jira/github) ticket to look into the issue?

Ok with examples being altered for now but it needs fixing

**Review by declankieran — APPROVED** [review]

**Comment by SheenaSharma** [comment]
>

**Comment by SheenaSharma** [comment]
> Do we have a (jira/github) ticket to look into the issue?
> 
> Ok with examples being altered for now but it needs fixing

 Raised a Jira ticket [IOPS-1612](https://nhsd-jira.digital.nhs.uk/browse/IOPS-1612)regarding this.

**Comment by SheenaSharma** [comment]
> Do we have a (jira/github) ticket to look into the issue?
> 
> Ok with examples being altered for now but it needs fixing

**Comment by SheenaSharma** [comment]
No longer required. Raised a new PR and added a new branch regarding this.

**Pull request closed without merging**
