### PR TITLE
Updated CodeSystems to add new codes for EPS

### PR DESCRIPTION
**Pull request by digitalhealthmartin**
**WARNING: THIS PR IS FOR NHS DIGITAL IG. DO NOT MERGE UNTIL REVIEWS ARE COMPLETE.**

Updated CodeSystem-medicationdispense-endorsement.json
- added code 'WR' / display 'Waste Reduction (Wales Only)'

Updated CodeSystem-prescription-charge-exemption.xml
- added code '1001' / display 'Welsh Prescription Welsh Dispenser – No Charge (Wales Only)'
- added code '1002' / display 'Welsh Entitlement Card (Wales Only)'
- minor tweak to format/tabs

Upped version and updated date for both assets.

### CODE REVIEW

**Review by marcusfearnett-nhsdigital — CHANGES_REQUESTED** [review]
looks like you've got a spurious </code> tag at L:148, L:152 of CodeSystem/CodeSystem-prescription-charge-exemption.xml
and all the checks have failed

**Comment by digitalhealthmartin** [comment]
Pushed a change where I fixed the display tag issue.

Also, although there are errors, it's not for the files I've updated.

According to the GitHub Action Log:

CodeSystem-medicationdispense-endorsement.json
      ✓ Check profiles are not present in resource (Implementation Guide Best Practice)
      ✓ Profile has no snapshot and Resource is present (1 ms)
      ✓ FHIR Validation (12 ms)

CodeSystem-prescription-charge-exemption.xml
      ✓ Check profiles are not present in resource (Implementation Guide Best Practice)
      ✓ Profile has no snapshot and Resource is present (1 ms)
      ✓ FHIR Validation (15 ms)

**Review by marcusfearnett-nhsdigital — APPROVED** [review]
still need to fix the checks at some point next sprint. if it's not passing, and we still merge there's little point in having the checks on. i have no desire to scroll through 4000 lines of validation run to work out what's breaking every time i get a pull request review.

**Comment by ryma2fhir** [comment]
I've just ran the NHSDigital main branch through the validator and it has the same 9 errors. As this is the deprecated branch I cannot see these every getting fixed. https://github.com/NHSDigital/NHSEngland-FHIR-ImplementationGuide/actions/runs/10318431824

The main branch (and programmes repo) is another matter and I'm looking at fixing those errors, with the questionnaire being a false positive.

**Comment by digitalhealthmartin** [comment]
> I've just ran the NHSDigital main branch through the validator and it has the same 9 errors. As this is the deprecated branch I cannot see these every getting fixed. https://github.com/NHSDigital/NHSEngland-FHIR-ImplementationGuide/actions/runs/10318431824
> 
> The main branch (and programmes repo) is another matter and I'm looking at fixing those errors, with the questionnaire being a false positive.

I agree - these are historical issues and this update isn't to fix historical issues but just to add new codes.

**Review by ryma2fhir — APPROVED** [review]

**Review by omarisgreat — APPROVED** [review]

**Pull request merged**
